# Generated by Django 4.0.5 on 2022-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gdpr_agreement',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='communication_agreement',
            field=models.BooleanField(default=True),
        ),
    ]
